# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mass_mandrill"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Trisignia", "Neboj\u{161}a Stri\u{10d}evi\u{107}"]
  s.date = "2013-04-18"
  s.description = "Send Mandrill template emails"
  s.email = "nebojsa.stricevic@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/mass_mandrill.rb",
    "lib/mass_mandrill/config.rb",
    "lib/mass_mandrill/mandrill_mail.rb",
    "lib/mass_mandrill/mandrill_mailer.rb",
    "mass_mandrill.gemspec",
    "spec/mass_mandrill/config_spec.rb",
    "spec/mass_mandrill/mandrill_mailer_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/trisignia/mass_mandrill"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Send Mandrill emails"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mandrill-api>, ["~> 1.0.16"])
      s.add_development_dependency(%q<rspec>, ["~> 2.13.0"])
      s.add_development_dependency(%q<debugger>, ["~> 1.5.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.3"])
    else
      s.add_dependency(%q<mandrill-api>, ["~> 1.0.16"])
      s.add_dependency(%q<rspec>, ["~> 2.13.0"])
      s.add_dependency(%q<debugger>, ["~> 1.5.0"])
      s.add_dependency(%q<rdoc>, ["~> 4.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<bundler>, ["~> 1.3.3"])
    end
  else
    s.add_dependency(%q<mandrill-api>, ["~> 1.0.16"])
    s.add_dependency(%q<rspec>, ["~> 2.13.0"])
    s.add_dependency(%q<debugger>, ["~> 1.5.0"])
    s.add_dependency(%q<rdoc>, ["~> 4.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<bundler>, ["~> 1.3.3"])
  end
end

